workflow:
  name: analyze-requirements
  version: "1.0.0"
  description: Comprehensive requirements analysis via specialized analysts

  entry_point: instructions.md

quality:
  analysis_quality_threshold: 6.0
  max_refine_attempts: 2
  enable_auto_refine: true

  scoring_criteria:
    requirements_completeness: 2.5
    business_value_clarity: 2.0
    stakeholder_alignment: 1.5
    feasibility_assessment: 1.5
    acceptance_criteria_quality: 1.5
    risk_identification: 1.0
  total_score: 10.0

analysis_areas:
  business_value_analyst:
    role: "Business goals, ROI, success metrics, KPIs"
    context_max: 150000

  stakeholder_analyst:
    role: "Stakeholder needs, constraints, expectations"
    context_max: 150000

  requirements_analyst:
    role: "Functional and non-functional requirements extraction"
    context_max: 150000

  feasibility_analyst:
    role: "Technical feasibility, resource requirements, risks"
    context_max: 150000

  acceptance_criteria_analyst:
    role: "Testable acceptance criteria, edge cases, validation"
    context_max: 150000

output:
  analysis_folder: "{project-root}/docs/business-analysis/"
  generate_business_case: true
  generate_requirements_doc: true
  generate_stakeholder_map: true
  generate_acceptance_criteria: true
  generate_risk_assessment: true

metadata:
  workflow_type: requirements_analysis
  autonomous: false
