# Validate Stories Workflow Configuration
# Enhanced-SM Module v1.0

workflow:
  name: validate-stories
  version: "1.0.0"
  description: Validates user stories for INVEST compliance, testability, and readiness for development

  entry_point: instructions.md

# Validation configuration
validation:
  invest_compliance:
    independent: true      # Can be developed independently
    negotiable: true       # Details can be discussed
    valuable: true         # Clear value to user/business
    estimable: true        # Can be estimated
    small: true            # Fits in sprint
    testable: true         # Has testable AC

  acceptance_criteria:
    min_count: 3
    must_be_testable: true
    must_be_measurable: true
    must_cover_edge_cases: true

  task_breakdown:
    min_tasks: 1
    require_test_tasks: true
    tasks_must_be_actionable: true

  dependencies:
    must_identify_blockers: true
    must_identify_prerequisites: true
    no_circular_dependencies: true
    technical_deps_documented: true

  test_strategy:
    require_unit_tests: true
    require_integration_tests: true
    require_e2e_tests: true
    require_coverage_goals: true

  definition_of_done:
    require_dod: true
    require_approval_process: true

# Quality thresholds
quality_thresholds:
  overall_quality_min: 6.0
  invest_compliance_min: 7.0
  ac_quality_min: 6.0
  test_strategy_min: 6.0

# Sub-SM spawning
sub_sm_spawning:
  quality_validator_sm:
    tool: Task
    subagent_type: general-purpose
    prompt_template: |
      You are Quality-Validator-SM, specialized in assessing user story quality.

      STORIES TO VALIDATE:
      {stories}

      YOUR TASK:
      Assess each story's quality across multiple dimensions.

      SCORING CRITERIA (1-10 scale):

      1. INVEST Compliance (weight: 2.0):
         - Independent: Can be developed independently?
         - Negotiable: Details can be discussed?
         - Valuable: Clear value to user?
         - Estimable: Can be estimated?
         - Small: Fits in sprint?
         - Testable: Has testable AC?

      2. Acceptance Criteria Quality (weight: 2.0):
         - At least 3 AC present?
         - All AC testable and measurable?
         - Edge cases covered?
         - Happy path + error scenarios?

      3. Task Breakdown Quality (weight: 1.5):
         - Clear, actionable tasks?
         - Nothing missing?
         - Test tasks included?
         - Realistic effort?

      4. Dependencies (weight: 1.5):
         - Blockers identified?
         - Prerequisites identified?
         - No circular deps?
         - Technical deps documented?

      5. Technical Notes (weight: 1.0):
         - Helpful implementation guidance?
         - Key decisions documented?
         - Performance considerations?

      6. Test Strategy (weight: 2.0):
         - Unit tests defined?
         - Integration tests defined?
         - e2e tests defined?
         - Coverage goals stated?

      OUTPUT FORMAT (for each story):
      ```yaml
      story_id: {id}
      scores:
        invest_compliance: {score}/10
        ac_quality: {score}/10
        task_breakdown: {score}/10
        dependencies: {score}/10
        technical_notes: {score}/10
        test_strategy: {score}/10
        total: {weighted_total}/10

      issues:
        - category: {invest|ac|tasks|deps|tech|test}
          severity: {high|medium|low}
          issue: "{description}"
          recommendation: "{how to fix}"

      invest_details:
        independent: {true|false} - {reason}
        negotiable: {true|false} - {reason}
        valuable: {true|false} - {reason}
        estimable: {true|false} - {reason}
        small: {true|false} - {reason}
        testable: {true|false} - {reason}

      ready_for_dev: {true|false}
      ```

      Return: Complete validation report for all stories

  dependency_validator_sm:
    tool: Task
    subagent_type: general-purpose
    prompt_template: |
      You are Dependency-Validator-SM, specialized in validating story dependencies.

      STORIES:
      {stories}

      DEPENDENCY GRAPH:
      {dependency_graph}

      YOUR TASK:
      Validate all dependencies are correct, complete, and resolvable.

      CHECKS:

      1. Completeness:
         - All blocking dependencies identified?
         - All prerequisite dependencies identified?
         - Technical dependencies documented?

      2. Correctness:
         - Dependencies make logical sense?
         - No impossible dependencies?
         - Dependencies align with epic structure?

      3. Circular Dependencies:
         - Detect any cycles in dependency graph
         - If found: identify cycle chains
         - Severity: CRITICAL (blocks development!)

      4. Resolvability:
         - Can dependencies be satisfied?
         - Are dependent stories defined?
         - Realistic sequencing possible?

      OUTPUT FORMAT:
      ```yaml
      validation_status: {PASS|FAIL}

      dependency_issues:
        - story_id: {id}
          issue_type: {missing|circular|invalid|unresolvable}
          severity: {critical|high|medium|low}
          description: "{what's wrong}"
          recommendation: "{how to fix}"

      circular_dependencies:
        - cycle: [STORY-1, STORY-5, STORY-3, STORY-1]
          severity: critical
          resolution: "{suggest which dependency to break}"

      missing_dependencies:
        - story_id: {id}
          missing_type: {blocker|prerequisite|technical}
          suggestion: "{what dependency should be added}"

      dependency_graph_valid: {true|false}
      ready_for_planning: {true|false}
      ```

      Return: Complete dependency validation report

  invest_validator_sm:
    tool: Task
    subagent_type: general-purpose
    prompt_template: |
      You are INVEST-Validator-SM, specialized in deep INVEST principle validation.

      STORIES:
      {stories}

      YOUR TASK:
      Rigorously validate each story against INVEST principles.

      INVEST CRITERIA:

      **Independent:**
      - Can be developed without waiting for other stories?
      - Has all necessary context?
      - Minimal coupling to other stories?

      **Negotiable:**
      - Implementation details flexible?
      - Room for developer input?
      - Not overly prescriptive?

      **Valuable:**
      - Clear value to user or business?
      - Measurable impact?
      - Aligns with product goals?

      **Estimable:**
      - Team can estimate effort?
      - Enough detail to estimate?
      - Not too ambiguous?

      **Small:**
      - Can complete in one sprint?
      - Points <= 13 (preferably <= 8)?
      - Can be split if too large?

      **Testable:**
      - Clear acceptance criteria?
      - AC measurable and verifiable?
      - Success/failure clearly defined?

      OUTPUT FORMAT:
      ```yaml
      story_id: {id}
      invest_compliance:
        independent:
          compliant: {true|false}
          score: {1-10}
          reason: "{explanation}"
          blockers: [{story_ids}]

        negotiable:
          compliant: {true|false}
          score: {1-10}
          reason: "{explanation}"
          overly_prescriptive: {true|false}

        valuable:
          compliant: {true|false}
          score: {1-10}
          reason: "{explanation}"
          value_proposition: "{what value}"

        estimable:
          compliant: {true|false}
          score: {1-10}
          reason: "{explanation}"
          estimation_blockers: ["{what's unclear}"]

        small:
          compliant: {true|false}
          score: {1-10}
          reason: "{explanation}"
          estimated_points: {points}
          should_split: {true|false}

        testable:
          compliant: {true|false}
          score: {1-10}
          reason: "{explanation}"
          testable_ac_count: {count}
          untestable_ac: ["{which AC not testable}"]

      overall_invest_score: {avg}/10
      invest_compliant: {true|false}
      issues: ["{list issues}"]
      recommendations: ["{list fixes}"]
      ```

      Return: Detailed INVEST validation for all stories

# Output configuration
output:
  validation_report_location: "{project-root}/.bmad/stories/validation-report.md"
  quality_scores_location: "{project-root}/.bmad/stories/quality-scores.yaml"
  issues_list_location: "{project-root}/.bmad/stories/validation-issues.md"

# Status tracking
status:
  status_file: "{status_location}/status.yaml"
  update_on_completion: true

metadata:
  workflow_type: validation
  autonomous: true
