#!/bin/bash

# SonarQube Issues Fix Script for Batch 2
# This script fixes common TypeScript issues in route files

cd /Users/raffael/Documents/GitHub/alu-crm

echo "=== Starting SonarQube Issue Fixes ==="
echo ""

# Counter for fixes
FIXED_S3863=0
FIXED_S7763=0
FIXED_S7726=0
FIXED_S7723=0
FIXED_S4325=0
FIXED_S1128=0

# Fix S7763: export...from pattern
echo "Fixing S7763: export...from pattern..."
find app/routes -name "*.tsx" -type f | while read file; do
  if grep -q "import { serverTimingHeaders } from \"~/modules/metrics/utils/defaultHeaders.server\";" "$file" 2>/dev/null && \
     grep -q "^export { serverTimingHeaders as headers };$" "$file" 2>/dev/null; then
    # Remove the import line
    sed -i '' '/^import { serverTimingHeaders } from "~\/modules\/metrics\/utils\/defaultHeaders\.server";$/d' "$file"
    # Replace the export line with combined export...from
    sed -i '' 's/^export { serverTimingHeaders as headers };$/export { serverTimingHeaders as headers } from "~\/modules\/metrics\/utils\/defaultHeaders.server";/' "$file"
    echo "  Fixed: $file"
    ((FIXED_S7763++))
  fi
done
echo "  Total S7763 fixes: $FIXED_S7763"
echo ""

# Fix S7723: Use new Error() instead of Error()
echo "Fixing S7723: new Error() constructor..." >&2
find app/routes -name "*.tsx" -type f | while read file; do
  if grep -q "throw Error(" "$file" 2>/dev/null; then
    sed -i '' 's/throw Error(/throw new Error(/g' "$file"
    echo "  Fixed: $file" >&2
    ((FIXED_S7723++))
  fi
done
echo "  Total S7723 fixes: $FIXED_S7723" >&2
echo "" >&2

# Fix S4325: Remove unnecessary type assertions (! operator)
echo "Fixing S4325: Remove unnecessary type assertions..."
find app/routes -name "*.tsx" -type f | while read file; do
  # This is a more complex fix, we'll skip for now to avoid breaking code
  # Manual review is recommended for these cases
  :
done
echo "  S4325: Skipped (requires manual review)"
echo ""

# Fix S7726: Name arrow functions in exports
echo "Fixing S7726: Name arrow functions..."
# This requires context-specific naming, already done for autogenerated files
echo "  S7726: Partially done (autogenerated files completed)"
echo ""

echo "=== Summary ===" >&2
echo "S7763 (export...from): $FIXED_S7763 files" >&2
echo "S7723 (new Error): $FIXED_S7723 files" >&2
echo "S7726 (named functions): Partially completed" >&2
echo "" >&2
echo "=== Done ===" >&2
