name: enhanced-dev-story
description: "Orchestrate story development using sub-developer pattern with isolated contexts, auto-testing, auto-fixes, and status tracking"
author: "Enhanced Dev Module"
entry_point: instructions.md

# Critical variables from config
config_source: "{project-root}/bmad/enhanced-dev/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"

# Story and context configuration
story_file: "" # Auto-discovered from BMM status or explicitly provided
story_dir: "{project-root}/stories"
context_file: "{story_dir}/{{story_key}}.context.xml"

# Enhanced dev status tracking
status_file: "{project-root}/.bmad/enhanced-dev/status.yaml"
status_template: "{project-root}/bmad/enhanced-dev/status/dev-status-template.yaml"

# Retry and anti-loop configuration
max_task_retries: 3
max_fix_retries: 3
max_loop_iterations: 10
task_timeout_minutes: 15

# AI-Team collaboration
shared_status_file: "{project-root}/.bmad-shared-status.yaml"
use_enhanced_agents: true  # Prefer enhanced agents over generic sub-agents

# Competitive dual-agent pattern
competitive_mode:
  enabled: true
  trigger_on: ["critical", "complex"]  # When to use competitive pattern
  auto_select_winner: false  # false = ask user to choose
  comparison_criteria: ["code_quality", "test_coverage", "readability", "performance"]

# Auto code-review
auto_code_review:
  enabled: true
  trigger_after_implementation: true
  reviewer_agent: "{project-root}/bmad/enhanced-code-review/agents/master-code-reviewer.md"
  max_review_iterations: 1  # Don't loop - present to user after 1 review

# Visual Testing & Documentation (Frontend)
visual_testing: "{config_source}:visual_testing"
artifacts_root: "{config_source}:visual_testing.artifacts_root"
screenshots: "{config_source}:visual_testing.screenshots"
e2e: "{config_source}:visual_testing.e2e"
components: "{config_source}:visual_testing.components"
timeline: "{config_source}:visual_testing.timeline"
performance: "{config_source}:visual_testing.performance"
a11y: "{config_source}:visual_testing.a11y"
auto_index: "{config_source}:visual_testing.auto_index"

# Research delegation
auto_research:
  enabled: true
  researcher_agent: "{project-root}/bmad/enhanced-research/agents/master-researcher.md"
  trigger_on_uncertainty: true  # When agent needs to research libraries, patterns, etc.

# Testing configuration
run_tests_command: "npm test"
test_coverage_threshold: 80
test_types:
  - unit
  - integration
  # e2e is separate task

# Git integration
auto_commit: true
commit_on_task_complete: true
commit_message_template: "feat: {task_description}\n\n- Implemented {task_id}\n- Tests: {test_status}\n- Coverage: {coverage}%\n\n🤖 Generated by Enhanced Dev"

# Deployment configuration
auto_deploy: false  # User must trigger deploy workflow
deploy_on_story_complete: false

# Workflow components
installed_path: "{project-root}/bmad/enhanced-dev/workflows/dev-story"
instructions: "{installed_path}/instructions.md"
checklist: "{installed_path}/checklist.md"

standalone: true
