# Plan Sprint Workflow Configuration
# Enhanced-SM Module v1.0

workflow:
  name: plan-sprint
  version: "1.0.0"
  description: Plans sprint with capacity awareness, dependency resolution, and story prioritization

  entry_point: instructions.md

# Sprint configuration
sprint:
  default_duration_weeks: 2
  default_capacity_points: 40  # Can be overridden by user input
  velocity_calculation: last_3_sprints  # Options: last_3_sprints, last_sprint, manual

  capacity_buffer: 0.8  # Plan to 80% capacity to allow for unknowns

# Team configuration (defaults - can be overridden)
team:
  default_team_size: 5
  default_velocity: 40  # points per sprint
  availability_factor: 1.0  # 1.0 = full availability, 0.8 = 20% reduced

# Prioritization criteria
prioritization:
  business_value:
    weight: 3.0
    factors:
      - user_impact
      - revenue_impact
      - strategic_alignment

  dependencies:
    weight: 2.5
    priority: blockers_first  # Prioritize stories that block others

  risk:
    weight: 1.5
    factors:
      - technical_risk
      - unknown_complexity
      - external_dependencies

  effort:
    weight: 1.0
    strategy: balance  # Options: balance, small_first, large_first

# Sub-SM spawning
sub_sm_spawning:
  capacity_analyzer_sm:
    tool: Task
    subagent_type: general-purpose
    prompt_template: |
      You are Capacity-Analyzer-SM, specialized in analyzing team capacity and velocity.

      TEAM DATA:
      {team_data}

      HISTORICAL VELOCITY:
      {velocity_history}

      YOUR TASK:
      Calculate realistic sprint capacity based on team data and historical velocity.

      ANALYSIS:

      1. Historical Velocity:
         - Last sprint: {sprint_1} points
         - 2 sprints ago: {sprint_2} points
         - 3 sprints ago: {sprint_3} points
         - Average: {avg} points

      2. Team Availability:
         - Team size: {size}
         - Sprint duration: {weeks} weeks
         - Holidays/PTO: {pto_days} days
         - Meetings/overhead: {overhead_percentage}%
         - Effective availability: {effective}%

      3. Capacity Calculation:
         - Base velocity: {avg_velocity}
         - Availability factor: {availability}
         - Buffer factor: {buffer} (recommend 0.8 for safety)
         - **Recommended capacity: {capacity} points**

      OUTPUT FORMAT:
      ```yaml
      capacity_analysis:
        historical_velocity:
          last_sprint: {points}
          last_3_avg: {points}
          trend: {increasing|stable|decreasing}

        team_capacity:
          team_size: {count}
          sprint_duration: {weeks}
          availability: {percentage}%
          effective_capacity: {points}

        recommendations:
          target_capacity: {points}
          buffer: {percentage}%
          confidence: {high|medium|low}

        risks:
          - {risk_1}
          - {risk_2}
      ```

      Return: Capacity analysis

  story_prioritizer_sm:
    tool: Task
    subagent_type: general-purpose
    prompt_template: |
      You are Story-Prioritizer-SM, specialized in story prioritization for sprint planning.

      STORIES:
      {stories}

      DEPENDENCY GRAPH:
      {dependency_graph}

      EPIC PRIORITIES:
      {epic_priorities}

      YOUR TASK:
      Prioritize stories for sprint planning based on multiple criteria.

      PRIORITIZATION CRITERIA:

      1. Business Value (weight: 3.0):
         - User impact (high/medium/low)
         - Revenue impact
         - Strategic alignment

      2. Dependencies (weight: 2.5):
         - Blockers first (stories that block many others)
         - Prerequisites before dependents
         - Minimize dependency chains within sprint

      3. Risk (weight: 1.5):
         - Technical risk
         - Unknown complexity
         - External dependencies

      4. Effort (weight: 1.0):
         - Balance: Mix of small, medium, large
         - Fits capacity constraints

      PRIORITIZATION STRATEGY:
      - Must-haves (blockers, high value) first
      - Should-haves (dependencies, medium value) second
      - Nice-to-haves (independent, lower value) last

      OUTPUT FORMAT:
      ```yaml
      prioritized_stories:
        - story_id: "STORY-1"
          priority_score: 8.5
          priority_tier: "must_have"
          rationale: "Blocks 5 other stories, high user impact"
          estimated_points: 5

        - story_id: "STORY-3"
          priority_score: 7.8
          priority_tier: "should_have"
          rationale: "Required for epic-2, medium complexity"
          estimated_points: 8

        - ...

      priority_tiers:
        must_have: {count} stories, {total_points} points
        should_have: {count} stories, {total_points} points
        nice_to_have: {count} stories, {total_points} points

      recommendations:
        - "Prioritize STORY-1 first (blocks many)"
        - "Group STORY-5, STORY-7 (same epic)"
        - "Defer STORY-12 (no dependencies, low value)"
      ```

      Return: Prioritized story list

  sprint_planner_sm:
    tool: Task
    subagent_type: general-purpose
    prompt_template: |
      You are Sprint-Planner-SM, specialized in creating optimal sprint plans.

      CAPACITY:
      {capacity_analysis}

      PRIORITIZED STORIES:
      {prioritized_stories}

      DEPENDENCY GRAPH:
      {dependency_graph}

      YOUR TASK:
      Create sprint plan(s) that maximize value delivery while respecting capacity and dependencies.

      PLANNING RULES:

      1. Capacity Constraint:
         - Total points <= capacity
         - Leave ~20% buffer for unknowns

      2. Dependency Constraint:
         - Include prerequisite stories before dependents
         - Minimize cross-sprint dependencies

      3. Epic Coherence:
         - Keep related stories together when possible
         - Complete full epics when feasible

      4. Value Maximization:
         - Prioritize high-value stories
         - Balance quick wins with strategic work

      PLANNING PROCESS:

      1. Start with Sprint 1
      2. Add must-have stories (respecting dependencies)
      3. Fill with should-haves until capacity reached
      4. Create Sprint 2 with remaining stories
      5. Continue until all stories planned or backlog

      OUTPUT FORMAT:
      ```yaml
      sprint_plan:
        sprint_1:
          duration: {weeks} weeks
          capacity: {points}
          stories:
            - story_id: "STORY-1"
              title: "User Login"
              points: 5
              priority: "must_have"
              dependencies_satisfied: true

            - story_id: "STORY-3"
              title: "Password Reset"
              points: 3
              priority: "should_have"
              dependencies_satisfied: true

            - ...

          totals:
            story_count: {count}
            total_points: {points}
            capacity_utilization: {percentage}%
            epics_covered: [{epic_ids}]

          risks:
            - {risk_1}
            - {risk_2}

        sprint_2:
          {same structure}

        backlog:
          stories: [{story_ids}]
          total_points: {points}
          reason: "Lower priority, capacity constraints"

      summary:
        total_sprints: {count}
        total_stories_planned: {count}
        total_points_planned: {points}
        backlog_count: {count}
        avg_capacity_utilization: {percentage}%

      recommendations:
        - {recommendation_1}
        - {recommendation_2}
      ```

      Return: Complete sprint plan

# Output configuration
output:
  sprint_plan_location: "{project-root}/.bmad/sprint-plan.md"
  capacity_analysis_location: "{project-root}/.bmad/capacity-analysis.yaml"
  backlog_location: "{project-root}/.bmad/backlog.md"

# Status tracking
status:
  status_file: "{status_location}/status.yaml"
  update_on_completion: true

metadata:
  workflow_type: sprint_planning
  autonomous: true
