# Create Stories Workflow Configuration
# Enhanced-SM Module v1.0

workflow:
  name: create-stories
  version: "1.0.0"
  description: Creates user stories from epic files using dynamic batching and quality-based refinement

  entry_point: instructions.md
  checklist: checklist.md

# Story batching configuration (dynamic based on complexity)
story_batching:
  simple_batch_size: 10      # Stories with 1-2 tasks, 1-3 points
  medium_batch_size: 5       # Stories with 3-5 tasks, 5-8 points
  complex_batch_size: 2      # Stories with 6+ tasks, 13+ points

  complexity_thresholds:
    simple_max_tasks: 2
    simple_max_points: 3
    medium_max_tasks: 5
    medium_max_points: 8
    complex_min_tasks: 6
    complex_min_points: 13

# Quality configuration
quality:
  story_quality_threshold: 6.0  # Overridden by config.yaml if present
  max_refine_attempts: 2
  enable_auto_refine: true

  scoring_criteria:
    invest_compliance: 2.0       # Independent, Negotiable, Valuable, Estimable, Small, Testable
    acceptance_criteria: 2.0     # Complete, testable, measurable
    task_breakdown: 1.5          # Clear, actionable, complete
    dependencies: 1.5            # Identified and documented
    technical_notes: 1.0         # Helpful implementation guidance
    test_strategy: 2.0           # Unit, integration, e2e defined

  total_score: 10.0

# Sub-SM spawning configuration
sub_sm_spawning:
  story_writer_sm:
    tool: Task
    subagent_type: general-purpose
    context_max: 150000
    prompt_template: |
      You are Story-Writer-SM, a specialized Scrum Master focused on writing high-quality user stories.

      YOUR TASK:
      Write {batch_size} user stories for the following epic requirements.

      EPIC CONTEXT:
      {epic_content}

      REQUIREMENTS TO ADDRESS:
      {requirements_list}

      OTHER STORIES CONTEXT (for dependency awareness):
      {other_stories_context}

      OUTPUT FORMAT (for each story):
      ```markdown
      # Story: {title}

      **Epic:** {epic_id} ({epic_title})
      **Story ID:** {story_id}
      **Priority:** {High|Medium|Low}
      **Estimated Points:** {1|2|3|5|8|13|21}

      ## User Story
      As a **{user_role}**
      I want to **{action}**
      So that **{benefit}**

      ## Acceptance Criteria
      - [ ] {criterion_1}
      - [ ] {criterion_2}
      - [ ] {criterion_3}
      ...

      ## Tasks
      1. {task_1}
      2. {task_2}
      3. {task_3}
      ...

      ## Dependencies
      - **Blocks:** [{story_ids}]
      - **Depends On:** [{story_ids}]

      ## Technical Notes
      {implementation_guidance}

      ## Test Strategy
      - Unit: {what_to_test}
      - Integration: {what_to_test}
      - e2e: {what_to_test}

      ## Definition of Done
      - [ ] All tasks completed
      - [ ] All AC met
      - [ ] Unit tests pass (coverage > 80%)
      - [ ] e2e tests pass
      - [ ] Code reviewed
      - [ ] Deployed to staging
      - [ ] PM approved
      ```

      REQUIREMENTS:
      1. INVEST compliance (Independent, Negotiable, Valuable, Estimable, Small, Testable)
      2. Acceptance criteria MUST be testable and measurable
      3. Tasks MUST be clear, actionable, complete
      4. Identify dependencies (blocks, depends on)
      5. Estimate story points realistically
      6. Define test strategy (unit, integration, e2e)

      After writing all stories, provide a QUALITY SELF-ASSESSMENT (1-10 scale):
      - INVEST Compliance: {score}/10
      - AC Quality: {score}/10
      - Task Breakdown: {score}/10
      - Dependencies: {score}/10
      - Technical Notes: {score}/10
      - Test Strategy: {score}/10
      - **TOTAL SCORE:** {total}/10

      Return: JSON array of story objects + quality assessment

  refine_story_sm:
    tool: Task
    subagent_type: general-purpose
    context_max: 150000
    prompt_template: |
      You are Refine-Story-SM, specialized in improving story quality based on feedback.

      ORIGINAL STORY:
      {story_content}

      QUALITY ISSUES IDENTIFIED:
      {feedback}

      YOUR TASK:
      Refine the story to address all quality issues while maintaining the core intent.

      Focus on:
      - Making AC more testable and measurable
      - Clarifying and completing task breakdown
      - Identifying missing dependencies
      - Improving technical notes
      - Strengthening test strategy

      Return: Refined story + new quality score

  dependency_analyzer_sm:
    tool: Task
    subagent_type: general-purpose
    context_max: 150000
    prompt_template: |
      You are Dependency-Analyzer-SM, specialized in detecting story and epic dependencies.

      ALL STORIES:
      {all_stories}

      EPIC STRUCTURE:
      {epic_structure}

      YOUR TASK:
      1. Identify story-to-story dependencies (blocks, depends_on)
      2. Identify epic-level dependencies
      3. Identify technical dependencies (database, services, infrastructure)
      4. Detect circular dependencies (ERROR if found)

      OUTPUT FORMAT:
      ```yaml
      story_dependencies:
        STORY-1:
          blocks: [STORY-2, STORY-5]
          depends_on: []
        STORY-2:
          blocks: []
          depends_on: [STORY-1]
        ...

      epic_dependencies:
        Epic-2:
          depends_on: [Epic-1]
        ...

      technical_dependencies:
        - name: "Auth Service"
          required_by: [STORY-1, STORY-3, STORY-4]
        - name: "Database Schema v2"
          required_by: [STORY-7, STORY-8]
        ...

      circular_dependencies: []  # or list of cycles if found

      dependency_graph:
        {graphviz or mermaid format}
      ```

      Return: Complete dependency analysis

# Anti-loop guards
guards:
  max_refine_iterations: 2
  batch_timeout_minutes: 20
  story_creation_timeout_minutes: 15
  total_workflow_timeout_minutes: 120

  on_timeout:
    action: skip_and_continue
    log_warning: true
    mark_status: blocked

# Output configuration
output:
  story_files_location: "{project-root}/.bmad/stories/"
  story_file_naming: "story-{story_id}-{slug}.md"
  dependency_graph_location: "{project-root}/.bmad/stories/dependency-graph.yaml"
  batch_summary_location: "{project-root}/.bmad/stories/batch-summary.md"

  bmm_compatible: true  # Story format matches BMM expectations

# Status tracking
status:
  status_file: "{status_location}/status.yaml"
  update_frequency: after_each_batch

  tracked_metrics:
    - total_stories
    - stories_completed
    - stories_validated
    - stories_needing_refinement
    - batches_completed
    - batches_total
    - avg_quality_score
    - stories_below_threshold

# Integration
integration:
  input_source: epic_files
  input_location: "{project-root}/docs/epics/*.md"
  epic_format: enhanced-pm  # or bmm-pm

  handoff_to: enhanced-dev
  handoff_format: story_files

# Validation
validation:
  enforce_invest: true
  require_testable_ac: true
  require_task_breakdown: true
  require_dependencies: true
  require_test_strategy: true
  require_dod: true

  min_ac_count: 3
  min_task_count: 1
  max_story_points: 21  # Stories > 21 points should be split

metadata:
  workflow_type: story_creation
  supports_refinement: true
  supports_batching: true
  autonomous: true
