# Create Architecture Workflow Configuration
# Enhanced-Architect Module v1.0

workflow:
  name: create-architecture
  version: "1.0.0"
  description: Creates comprehensive system architecture using specialized sub-architects

  entry_point: instructions.md
  checklist: checklist.md

# Architecture component batching
component_batching:
  simple_batch_size: 8   # Utilities, configs, helpers
  medium_batch_size: 4   # Services, controllers, models
  complex_batch_size: 2  # Core systems, integrations

  complexity_thresholds:
    simple_max_dependencies: 2
    simple_max_integrations: 1
    medium_max_dependencies: 5
    medium_max_integrations: 3
    complex_min_dependencies: 6
    complex_min_integrations: 4

# Quality configuration
quality:
  architecture_quality_threshold: 6.0
  max_refine_attempts: 2
  enable_auto_refine: true

  scoring_criteria:
    clarity_completeness: 2.0
    scalability_performance: 2.0
    security_design: 2.0
    technology_justification: 1.5
    integration_patterns: 1.5
    deployment_feasibility: 1.0
  total_score: 10.0

# Interactive decision configuration
interactive_decisions:
  enable: true
  auto_approve_simple: false
  decision_timeout_seconds: 300

  critical_decisions:
    - technology_stack
    - architecture_pattern
    - database_choice
    - deployment_strategy
    - security_approach
    - integration_pattern

# Sub-architect spawning
sub_architects:
  system_architect:
    role: "High-level system design and technology decisions"
    context_max: 150000

  component_architect:
    role: "Service/module architecture and design patterns"
    context_max: 150000

  data_architect:
    role: "Database design, data flow, and schema architecture"
    context_max: 150000

  security_architect:
    role: "Security patterns, auth, encryption, threat modeling"
    context_max: 150000

  integration_architect:
    role: "API design, microservices, event patterns"
    context_max: 150000

  deployment_architect:
    role: "Infrastructure, CI/CD, scaling, monitoring"
    context_max: 150000

# Output configuration
output:
  architecture_folder: "{project-root}/docs/architecture/"
  adr_folder: "{project-root}/docs/architecture/adrs/"
  diagrams_folder: "{project-root}/docs/architecture/diagrams/"

  generate_complete_doc: true
  generate_component_docs: true
  generate_adrs: true
  generate_diagrams: true

  diagram_format: "mermaid"
  bmm_compatible: true

# Status tracking
status:
  status_file: "{status_location}/status.yaml"
  update_frequency: after_each_phase

# Validation
validation:
  enforce_consistency: true
  require_technology_justification: true
  require_security_considerations: true
  require_scalability_analysis: true
  require_deployment_plan: true

metadata:
  workflow_type: architecture_creation
  supports_refinement: true
  supports_batching: true
  autonomous: false  # Requires user decisions
