workflow:
  name: review-code
  version: "1.0.0"
  description: Comprehensive code review via specialized reviewers

  entry_point: instructions.md

quality:
  review_quality_threshold: 6.0
  severity_levels:
    blocker: "Must fix before merge"
    critical: "Should fix before merge"
    major: "Should fix soon"
    minor: "Consider fixing"
    suggestion: "Nice to have"

review_aspects:
  security_review:
    role: "Security vulnerabilities, auth, data validation"
    weight: 2.5
    context_max: 150000

  performance_review:
    role: "Performance bottlenecks, optimization opportunities"
    weight: 2.0
    context_max: 150000

  test_coverage_review:
    role: "Test completeness, edge cases, test quality"
    weight: 2.0
    context_max: 150000

  code_quality_review:
    role: "Clean code principles, SOLID, DRY, maintainability"
    weight: 1.5
    context_max: 150000

  architecture_review:
    role: "Architecture patterns, separation of concerns"
    weight: 1.5
    context_max: 150000

  documentation_review:
    role: "Code comments, API docs, README updates"
    weight: 0.5
    context_max: 150000

output:
  review_file: "{project-root}/.bmad/enhanced-code-review/review-{story_id}.md"
  append_to_story: true
  create_github_comments: false
  generate_metrics: true

metadata:
  workflow_type: code_review
  autonomous: true
