import { Tenant } from "@prisma/client";
import { LoaderFunctionArgs, redirect, ActionFunction } from "react-router";
import { MetaTagsDto } from "~/application/dtos/seo/MetaTagsDto";
import { RowAccess } from "~/application/enums/entities/RowAccess";
import { EntitiesApi } from "~/utils/api/.server/EntitiesApi";
import { RowPermissionsApi } from "~/utils/api/.server/RowPermissionsApi";
import { RowsApi } from "~/utils/api/.server/RowsApi";
import UrlUtils from "~/utils/app/UrlUtils";
import { adminGetAllTenants, getTenant } from "~/utils/db/tenants.db.server";
import { UserWithDetails, getUser, getUsersByTenant } from "~/utils/db/users.db.server";
import RowHelper from "~/utils/helpers/RowHelper";
import RowsRequestUtils from "../utils/RowsRequestUtils";

export namespace Rows_Share {
  export type LoaderData = {
    meta: MetaTagsDto;
    rowData: RowsApi.GetRowData;
    routes: EntitiesApi.Routes;
    tenants: Tenant[];
    users: UserWithDetails[];
  };
  export const loader = async ({ request, params }: LoaderFunctionArgs) => {
    const { t, userId, tenantId, entity } = await RowsRequestUtils.getLoader({ request, params });
    if (!entity.isAutogenerated || entity.type === "system") {
      throw redirect(tenantId ? UrlUtils.currentTenantUrl(params, "404") : "/404");
    }
    const rowData = await RowsApi.get(params.id, {
      entity,
      tenantId,
      userId,
    });
    if (rowData.item.createdByUserId !== userId) {
      const user = await getUser(userId);
      if (!user?.admin) {
        throw new Error(t("shared.unauthorized"));
      }
    }
    let tenants: Tenant[] = [];
    if (tenantId) {
      const tenant = await getTenant(tenantId);
      if (tenant) {
        tenants.push(tenant);
      }
    } else {
      tenants = await adminGetAllTenants();
    }
    const data: LoaderData = {
      meta: [{ title: `${t("shared.share")} | ${RowHelper.getTextDescription({ entity, item: rowData.item, t })} | ${process.env.APP_NAME}` }],
      rowData,
      routes: EntitiesApi.getNoCodeRoutes({ request, params }),
      tenants,
      users: (await getUsersByTenant(tenantId)).filter((f) => f.id !== userId),
    };
    return Response.json(data);
  };

  export const action: ActionFunction = async ({ request, params }) => {
    const { t, entity, tenantId, userId, form } = await RowsRequestUtils.getAction({ request, params });
    const action = form.get("action");
    if (!entity.isAutogenerated || entity.type === "system") {
      throw redirect(tenantId ? UrlUtils.currentTenantUrl(params, "404") : "/404");
    }
    const rowData = await RowsApi.get(params.id, {
      entity,
      tenantId,
      userId,
    });

    if (action === "share") {
      const typeValue = form.get("type");
      if (typeof typeValue === "object" && typeValue !== null) {
        return Response.json({ error: t("shared.invalidForm") }, { status: 400 });
      }
      const type = typeValue?.toString() as "tenant" | "user" | "role" | "group" | "public";
      const idValue = form.get("id");
      if (typeof idValue === "object" && idValue !== null) {
        return Response.json({ error: t("shared.invalidForm") }, { status: 400 });
      }
      const id = idValue?.toString() ?? "";
      const accessValue = form.get("access");
      if (typeof accessValue === "object" && accessValue !== null) {
        return Response.json({ error: t("shared.invalidForm") }, { status: 400 });
      }
      const access = accessValue?.toString() as RowAccess;
      try {
        await RowPermissionsApi.share(rowData.item, {
          type,
          id,
          access,
        });
        return Response.json({ success: t("shared.saved") });
      } catch (error: any) {
        return Response.json({ error: error.message }, { status: 400 });
      }
    } else if (action === "set-access") {
      const idValue = form.get("id");
      if (typeof idValue === "object" && idValue !== null) {
        return Response.json({ error: t("shared.invalidForm") }, { status: 400 });
      }
      const id = idValue?.toString() ?? "";
      const accessValue = form.get("access");
      if (typeof accessValue === "object" && accessValue !== null) {
        return Response.json({ error: t("shared.invalidForm") }, { status: 400 });
      }
      const access = accessValue?.toString() as RowAccess;
      await RowPermissionsApi.setAccess(id, access);
      return Response.json({ success: t("shared.saved") });
    } else if (action === "remove") {
      const idValue = form.get("id");
      if (typeof idValue === "object" && idValue !== null) {
        return Response.json({ error: t("shared.invalidForm") }, { status: 400 });
      }
      const id = idValue?.toString() ?? "";
      await RowPermissionsApi.del(id);
      return Response.json({ success: t("shared.deleted") });
    } else {
      return Response.json({ error: t("shared.invalidForm") }, { status: 400 });
    }
  };
}
