import { Tenant } from "@prisma/client";
import { LoaderFunctionArgs, redirect, ActionFunction } from "react-router";
import { MetaTagsDto } from "~/application/dtos/seo/MetaTagsDto";
import { RowAccess } from "~/application/enums/entities/RowAccess";
import { EntitiesApi } from "~/utils/api/.server/EntitiesApi";
import { RowPermissionsApi } from "~/utils/api/.server/RowPermissionsApi";
import { RowsApi } from "~/utils/api/.server/RowsApi";
import UrlUtils from "~/utils/app/UrlUtils";
import { adminGetAllTenants, getTenant } from "~/utils/db/tenants.db.server";
import { UserWithDetails, getUser, getUsersByTenant } from "~/utils/db/users.db.server";
import RowHelper from "~/utils/helpers/RowHelper";
import RowsRequestUtils from "../utils/RowsRequestUtils";

export namespace Rows_Share {
  export type LoaderData = {
    meta: MetaTagsDto;
    rowData: RowsApi.GetRowData;
    routes: EntitiesApi.Routes;
    tenants: Tenant[];
    users: UserWithDetails[];
  };
  export const loader = async ({ request, params }: LoaderFunctionArgs) => {
    const { t, userId, tenantId, entity } = await RowsRequestUtils.getLoader({ request, params });
    if (!entity.isAutogenerated || entity.type === "system") {
      throw redirect(tenantId ? UrlUtils.currentTenantUrl(params, "404") : "/404");
    }
    const rowData = await RowsApi.get(params.id, {
      entity,
      tenantId,
      userId,
    });
    if (rowData.item.createdByUserId !== userId) {
      const user = await getUser(userId);
      if (!user?.admin) {
        throw new Error(t("shared.unauthorized"));
      }
    }
    let tenants: Tenant[] = [];
    if (tenantId) {
      const tenant = await getTenant(tenantId);
      if (tenant) {
        tenants.push(tenant);
      }
    } else {
      tenants = await adminGetAllTenants();
    }
    const data: LoaderData = {
      meta: [{ title: `${t("shared.share")} | ${RowHelper.getTextDescription({ entity, item: rowData.item, t })} | ${process.env.APP_NAME}` }],
      rowData,
      routes: EntitiesApi.getNoCodeRoutes({ request, params }),
      tenants,
      users: (await getUsersByTenant(tenantId)).filter((f) => f.id !== userId),
    };
    return Response.json(data);
  };

  type ParsedAction = { kind: "share"; type: "tenant" | "user" | "role" | "group" | "public"; id: string; access: RowAccess } | { kind: "set-access"; id: string; access: RowAccess } | { kind: "remove"; id: string };

  function parseStringField(form: FormData, field: string, t: any) {
    const value = form.get(field);
    if (typeof value === "object" && value !== null) {
      throw Response.json({ error: t("shared.invalidForm") }, { status: 400 });
    }
    return value?.toString() ?? "";
  }

  function parseAction(form: FormData, t: any): ParsedAction | Response {
    const action = form.get("action");
    if (action === "share") {
      return {
        kind: "share",
        type: parseStringField(form, "type", t) as ParsedAction["type"],
        id: parseStringField(form, "id", t),
        access: parseStringField(form, "access", t) as RowAccess,
      };
    }
    if (action === "set-access") {
      return {
        kind: "set-access",
        id: parseStringField(form, "id", t),
        access: parseStringField(form, "access", t) as RowAccess,
      };
    }
    if (action === "remove") {
      return {
        kind: "remove",
        id: parseStringField(form, "id", t),
      };
    }
    return Response.json({ error: t("shared.invalidForm") }, { status: 400 });
  }

  export const action: ActionFunction = async ({ request, params }) => {
    const { t, entity, tenantId, userId, form } = await RowsRequestUtils.getAction({ request, params });
    const parsed = parseAction(form, t);
    if (parsed instanceof Response) {
      return parsed;
    }
    if (!entity.isAutogenerated || entity.type === "system") {
      throw redirect(tenantId ? UrlUtils.currentTenantUrl(params, "404") : "/404");
    }
    const rowData = await RowsApi.get(params.id, {
      entity,
      tenantId,
      userId,
    });

    if (parsed.kind === "share") {
      try {
        await RowPermissionsApi.share(rowData.item, {
          type: parsed.type,
          id: parsed.id,
          access: parsed.access,
        });
        return Response.json({ success: t("shared.saved") });
      } catch (error: any) {
        return Response.json({ error: error.message }, { status: 400 });
      }
    } else if (parsed.kind === "set-access") {
      await RowPermissionsApi.setAccess(parsed.id, parsed.access);
      return Response.json({ success: t("shared.saved") });
    } else if (parsed.kind === "remove") {
      await RowPermissionsApi.del(parsed.id);
      return Response.json({ success: t("shared.deleted") });
    } else {
      return Response.json({ error: t("shared.invalidForm") }, { status: 400 });
    }
  };
}
