import { EntityTag } from "@prisma/client";
import { LoaderFunctionArgs, redirect, ActionFunction } from "react-router";
import { MetaTagsDto } from "~/application/dtos/seo/MetaTagsDto";
import { Colors } from "~/application/enums/shared/Colors";
import { EntitiesApi } from "~/utils/api/.server/EntitiesApi";
import { RowsApi } from "~/utils/api/.server/RowsApi";
import UrlUtils from "~/utils/app/UrlUtils";
import { getEntityTags, getEntityTag, createEntityTag, updateEntityTag, deleteEntityTag, getEntityTagById } from "~/utils/db/entities/entityTags.db.server";
import { getRowTag, createRowTag, deleteRowTags } from "~/utils/db/entities/rowTags.db.server";
import RowHelper from "~/utils/helpers/RowHelper";
import RowsRequestUtils from "../utils/RowsRequestUtils";
import { CustomError } from "~/application/dtos/shared/CustomError";

export namespace Rows_Tags {
  export type LoaderData = {
    meta: MetaTagsDto;
    rowData: RowsApi.GetRowData;
    routes: EntitiesApi.Routes;
    tags: EntityTag[];
  };
  export const loader = async ({ request, params }: LoaderFunctionArgs) => {
    const { t, userId, tenantId, entity } = await RowsRequestUtils.getLoader({ request, params });
    if (!entity.isAutogenerated || entity.type === "system") {
      throw redirect(tenantId ? UrlUtils.currentTenantUrl(params, "404") : "/404");
    }
    const rowData = await RowsApi.get(params.id, {
      entity,
      tenantId,
      userId,
    });
    if (!rowData.rowPermissions.canUpdate) {
      throw Response.json(new CustomError("You can't update this row", { permissions: rowData.rowPermissions }), { status: 403 });
    }
    const data: LoaderData = {
      meta: [{ title: `${t("shared.tag")} | ${RowHelper.getTextDescription({ entity, item: rowData.item, t })} | ${process.env.APP_NAME}` }],
      rowData,
      tags: await getEntityTags(entity.id),
      routes: EntitiesApi.getNoCodeRoutes({ request, params }),
    };
    return Response.json(data);
  };

  const badRequest = (data: { error: string }) => Response.json(data, { status: 400 });

  async function handleNewTag(entityId: string, itemId: string, form: FormData) {
    const tagNameValue = form.get("tag-name");
    if (typeof tagNameValue === "object" && tagNameValue !== null) {
      throw new Error("Invalid form data");
    }
    const value = tagNameValue?.toString() ?? "";
    const color = Number(form.get("tag-color") ?? Colors.INDIGO);
    let tag = await getEntityTag(entityId, value);
    if (!tag) {
      tag = await createEntityTag({
        entityId,
        value,
        color,
      });
    }
    const existingTag = await getRowTag(itemId, value);
    if (tag && !existingTag) {
      await createRowTag({
        rowId: itemId,
        tagId: tag.id,
      });
    }
  }

  async function handleEditTag(form: FormData) {
    const tagIdValue = form.get("tag-id");
    if (typeof tagIdValue === "object" && tagIdValue !== null) {
      throw new Error("Invalid form data");
    }
    const id = tagIdValue?.toString() ?? "";
    const tagNameValue = form.get("tag-name");
    if (typeof tagNameValue === "object" && tagNameValue !== null) {
      throw new Error("Invalid form data");
    }
    const value = tagNameValue?.toString() ?? "";
    const color = Number(form.get("tag-color"));
    await updateEntityTag(id, {
      value,
      color,
    });
  }

  async function handleSetTag(itemId: string, form: FormData) {
    const tagIdValue = form.get("tag-id");
    if (typeof tagIdValue === "object" && tagIdValue !== null) {
      throw new Error("Invalid form data");
    }
    const id = tagIdValue?.toString() ?? "";
    const tagActionValue = form.get("tag-action");
    if (typeof tagActionValue === "object" && tagActionValue !== null) {
      throw new Error("Invalid form data");
    }
    const tagAction = tagActionValue?.toString() ?? "";
    if (tagAction === "add") {
      await createRowTag({
        rowId: itemId,
        tagId: id,
      });
    } else {
      await deleteRowTags(itemId, id);
    }
  }

  async function handleDeleteTag(form: FormData) {
    const tagIdValue = form.get("tag-id");
    if (typeof tagIdValue === "object" && tagIdValue !== null) {
      throw new Error("Invalid form data");
    }
    const id = tagIdValue?.toString() ?? "";
    const tag = await getEntityTagById(id);
    if (tag) {
      await deleteEntityTag(tag.id);
    }
  }

  export const action: ActionFunction = async ({ request, params }) => {
    const { t, userId, tenantId, entity, form } = await RowsRequestUtils.getAction({ request, params });
    const rowData = await RowsApi.get(params.id, {
      entity,
      tenantId,
      userId,
    });
    const action = form.get("action");
    const { item } = rowData;
    if (!rowData.rowPermissions.canUpdate) {
      throw Response.json(new CustomError("You can't update this row", { permissions: rowData.rowPermissions }), { status: 403 });
    }

    if (action === "new-tag") {
      await handleNewTag(entity.id, item.id, form);
      return Response.json({});
    }
    if (action === "edit-tag") {
      await handleEditTag(form);
      return Response.json({});
    }
    if (action === "set-tag") {
      await handleSetTag(item.id, form);
      return Response.json({});
    }
    if (action === "delete-tag") {
      await handleDeleteTag(form);
      return Response.json({});
    }

    return badRequest({ error: t("shared.invalidForm") });
  };
}
