workflow:
  name: comprehensive-research
  version: "1.0.0"
entry_point: instructions.md
  description: Comprehensive research via specialized sub-researchers

quality:
  research_quality_threshold: 6.0
  max_refine_attempts: 2
  enable_auto_refine: true

  scoring_criteria:
    source_credibility: 2.0
    insight_depth: 2.5
    data_accuracy: 2.0
    actionable_recommendations: 2.0
    synthesis_quality: 1.5
  total_score: 10.0

interactive_decisions:
  enable: true
  critical_decisions:
    - research_scope
    - research_depth
    - competitor_selection
    - market_selection
    - source_budget

sub_researchers:
  market_researcher:
    role: "Market size, trends, TAM/SAM/SOM analysis"
    context_max: 150000
    tools: [WebSearch, WebFetch]

  competitor_analyst:
    role: "Competitive intelligence, feature comparison, pricing"
    context_max: 150000
    tools: [WebSearch, WebFetch]

  tech_researcher:
    role: "Tech stack evaluation, feasibility assessment"
    context_max: 150000
    tools: [WebSearch, WebFetch]

  user_researcher:
    role: "User personas, pain points, jobs-to-be-done"
    context_max: 150000
    tools: [WebSearch, WebFetch]

  trend_analyst:
    role: "Viral trends, TikTok, App Store analysis"
    context_max: 150000
    tools: [WebSearch, WebFetch]

  insights_synthesizer:
    role: "Aggregate findings and extract actionable insights"
    context_max: 150000

output:
  research_folder: "{project-root}/docs/research/"
  generate_market_research: true
  generate_competitor_analysis: true
  generate_tech_feasibility: true
  generate_user_research: true
  generate_trend_analysis: true
  generate_synthesis_report: true

metadata:
  workflow_type: research
  autonomous: false
