workflow:
  name: create-ux-design
  version: "1.0.0"
  description: Creates comprehensive UX design via specialized sub-designers

  entry_point: instructions.md

quality:
  ux_quality_threshold: 6.0
  max_refine_attempts: 2
  enable_auto_refine: true

  scoring_criteria:
    user_experience: 2.5
    visual_design: 2.0
    accessibility: 1.5
    responsiveness: 1.5
    interaction_design: 1.5
    brand_consistency: 1.0
  total_score: 10.0

interactive_decisions:
  enable: true
  critical_decisions:
    - design_system_choice
    - component_framework
    - accessibility_level
    - responsive_breakpoints
    - animation_approach

sub_designers:
  visual_designer:
    role: "Visual design, colors, typography, branding"
    context_max: 150000

  interaction_designer:
    role: "User flows, interactions, micro-interactions"
    context_max: 150000

  accessibility_designer:
    role: "WCAG compliance, screen reader support, keyboard navigation"
    context_max: 150000

  responsive_designer:
    role: "Mobile-first design, breakpoints, adaptive layouts"
    context_max: 150000

output:
  design_folder: "{project-root}/docs/ux-design/"
  generate_design_system: true
  generate_component_library: true
  generate_user_flows: true
  generate_wireframes: true
  generate_mockups: true

metadata:
  workflow_type: ux_design_creation
  autonomous: false
